import Head from 'next/head';
import { useRouter } from 'next/router';

export default function Stream() {
  const router = useRouter();
  const { id, coursename } = router.query;
  const course = coursename?.toString().replace(/-/g, ' ');
  return (
    <div>
      <Head>
        <title>{course?.toUpperCase()}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center">
        <div className="flex flex-col items-center justify-center w-full">
          <h1 className="text-[4rem] pt-16">{course?.toUpperCase()} Stream</h1>
        </div>
      </main>
    </div>
  );
}
